### ISSUE TITLE
[Bug Report] plugin crash on velocity 3.3.0

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [CaaMoe/MultiLogin#141]
### Bug Description

plugin cannot work on velocity 3.3.0

### MultiLogin Version

0.6.7

### System Architecture

liunx/amd64

### Server Core

velocity

### Configuration file

https://paste.ubuntu.com/p/ZvMGrNh9Fp/

### Logs

https://paste.ubuntu.com/p/789fqKxkpx/

### Affected area

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by xiaoyueyoqwq** [comment]
I found the last [Actions build](https://github.com/CaaMoe/MultiLogin/actions/runs/7810918508) may fix this problem

**Comment by CaaMoe** [comment]
so whats the problem

**Comment by xiaoyueyoqwq** [comment]
> so whats the problem

the last release plugin cannot work in the newest velocity and print the err log 'java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerLogin' and shutted down the proxy
the err logs are already in issue report

**Comment by Becods** [comment]
Fixed in the development version, please wait for release.
